version: "3"

services:
  autoconf:
    image: appgwreg.azurecr.io/modsecurity:latest
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - ./:/microsoft/modsecurity
    working_dir: /microsoft/modsecurity
    entrypoint: ./autogen.sh

  configure:
    image: appgwreg.azurecr.io/modsecurity:latest
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - ./:/microsoft/modsecurity
    working_dir: /microsoft/modsecurity
    entrypoint: 
      - ./configure
      - CXXFLAGS=-std=c++14
      - CFLAGS=-fPIC
      - --enable-standalone-module
      - --disable-mlogc

  make:
    image: appgwreg.azurecr.io/modsecurity:latest 
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - ./:/microsoft/modsecurity
    working_dir: /microsoft/modsecurity
    entrypoint: make
