name: CI

# Controls when the workflow will run
permissions:
  id-token: write
  contents: read
on:
  # Triggers the workflow on push or pull request events but only for the waf_nginx branch
  push:
    branches: [ waf_nginx ]
  pull_request:
    branches: [ waf_nginx ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Logging into appgwreg
      # Logs into Azure Registry
      - name: Azure Login
        uses: Azure/login@v2.0.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                
      # Runs make commands
      - name: Pull Image and Compile
        env:
          REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
          REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
          
        run: |
          az acr login --name $REGISTRY_NAME
          docker pull $AZURE_REGISTRY_DOMAIN/modsecurity:latest
          docker-compose run --rm autoconf
          docker-compose run --rm configure
          docker-compose run --rm make
